language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script: gulp
deploy:
  provider: s3
  access_key_id: AKIAI46PG2F5VPEPA3CQ
  secret_access_key:
    secure: Dc3nka1uoD5/xqfCNisV3dbU7lkC1MKezHGxxpZNzX0qUNt9K9uVVm4wUutPQzxLxRGLXRhZcW7wcCZStP2UazpJgii9k66vLMwYEVYqXTO+rlWeTC4yeSTmnWRYeGnsW1A33Noo6KduBQZL3f3g5OR+24VNPkC/BWLLSLCLU9PYjhqAwn8t+CBhjfNyUKdTtlbOv9E5x+yUdQykQYJbLZBM/Gz70C4xcPhDHHvVmnQT27HI1GNfCsN+MwgGSKwI3tgOEW5tysfiNov8C0+dravwg+zGdydmDFKtOcSS8CDFuRUjVhVXQxmAH5i3I8GJiJq++7g+LCHHh69ZazcpSWeyI1uSG+gmaFMi9TenXLCfaL5fvNbKGVD7QlZQJKuSks40HCOS+SXcGv3adTqXuZzqk18QQidyWhxMmpdy1uuuNhkEC8k00Y+RCxFIr83d1TjQ/hYFDfa8DKBzfYiVEQHM58Cwu+ujtuRc+vkPerPE3+Y+BP9Dm71Ivb3uzQ7kooGWW9rrtEbo1hNSAuaIFIdjQSyZf2WJBMduJGY3G8EmWsFUaIEuYF5fi9lGVi3BOZkWbgWqh56F0PUyMc5ocpACdeOAdgn6lDthbzfP430kvTd6lSYP9p+BryL0OeLP8sjb2rwLmWx82Uw88F39o6a2kaLjuQZHqGNqXmL2qRw=
  bucket: islandanimation.mcbanderson.com
  acl: public_read
  skip_cleanup: true
  local_dir: dist
  region: us-east-1
